apps/income/urls.py
from django.urls import path

from . import views

app_name = "income"
urlpatterns = [
    path('',                views.income_list,     name='income_list'),
    path('create/',         views.income_create,   name='income_create'),
    path('update/<int:pk>', views.income_update,   name='income_update'),
    path('delete/<int:pk>', views.income_delete.as_view(), name='income_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.frontend.views import home, contact
from apps.worker.views import login, SignOutView

from django.conf.urls.i18n import i18n_patterns

admin.site.site_header = settings.SITE_HEADER
admin.site.site_title = settings.SITE_TITLE
admin.site.index_title = settings.INDEX_TITLE

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('summernote/', include('django_summernote.urls')),
    path('blog/', include('apps.blog.urls')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('login/', login, name='login'),
    path('logout/', SignOutView.as_view(), name='logout'),
    path('dashboard/', include('apps.dashboard.urls')),
    path('contact/', contact, name='contact'),
)

apps/income/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from core.abstract import PaymentModel


def validate_report_extension(value):
    if not value.name.endswith('.pdf'):
        raise ValidationError(_('Only PDF files allowed'))


class Income(PaymentModel):

    user = models.ForeignKey(
        User,
        verbose_name=_('user'),
        related_name='incomes',
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )
    invoice_file = models.FileField(
        _('invoice file'),
        upload_to='incomes/',
        validators=[validate_report_extension],
        blank=True,
        null=True
        )
    local = models.CharField(_('local'), blank=True, max_length=120)
    machine = models.CharField(_('machine'), blank=True, max_length=120, default='')

    class meta:
        verbose_name = _('Income')
        verbose_name_plural = _('Incomes')

    def __str__(self):
        return self.invoice_number

    def get_absolute_url(self):
        return reverse('income:income_update', kwargs={'pk': self.pk})

apps/income/forms.py
from django import forms

from apps.income.models import Income

from django.conf import settings

class IncomeForm(forms.ModelForm):
    class Meta:
        date_payment = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
        model = Income
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(IncomeForm, self).__init__(*args, **kwargs)

apps/income/views.py
from django.shortcuts import render

from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.db import IntegrityError
from django.shortcuts import render,  get_object_or_404, redirect
from django.http import (
    HttpResponseRedirect,
    HttpResponseNotFound
)
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import DeleteView

from core.mixins import StaffRequiredMixin

from apps.expense.models import Expense

from .models import Income
from .forms import IncomeForm

from webpush import send_group_notification

@user_passes_test(lambda u: u.is_staff)
def income_create(request):
    if request.method == 'POST':
        form = IncomeForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.user = request.user
            item.save()
            messages.success(request, _('Income was successfully Created!'))
            return redirect('income:income_list')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        form = IncomeForm()

    context = {
        'form': form
    }

    payload = {'head': 'Welcome!', 'body': 'Hello World', 'icon': 'https://i.imgur.com/dRDxiCQ.png', 'url': 'https://www.example.com'}

    send_group_notification(user='admin', payload=payload, ttl=1000)

    return render(request, 'income/income_form.html', context)


@user_passes_test(lambda u: u.is_staff)
def income_list(request):
    expense_list = Expense.objects.all().order_by('date', 'invoice_number')
    income_list = Income.objects.all().order_by('date', 'invoice_number')

    context = {
        'expense_list': expense_list,
        'income_list': income_list,
    }
    return render(request, 'income/income_list.html', context)


@user_passes_test(lambda u: u.is_staff)
def income_update(request, pk):
    instance = get_object_or_404(Income, pk=pk)

    if request.method == 'POST':
        if 'copy' in request.POST:
            form = IncomeForm(request.POST, request.FILES)
        else:
            form = IncomeForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            messages.success(request, _('income was successfully Update!'))
            return redirect('income:income_list')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        form = IncomeForm(instance=instance)

    context = {
        'plugins': ['datepicker', ],
        'object': instance,
        'form': form,
        'update':True
    }
    return render(request,  'income/income_form.html', context)


class income_delete(StaffRequiredMixin, DeleteView):

    model = Income
    # por defecto busca MODEL_confirm_delete.html
    # template_name = 'settings/status_detete.html'
    success_url = reverse_lazy('income:income_list')

    def delete(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
            messages.success(request, _("Item {} deleted").format(self.object.invoice_number))
            self.object.delete()
            return HttpResponseRedirect(self.get_success_url())
        except IntegrityError:
            return HttpResponseNotFound()

apps/income/templates/income/income_confirm_delete.html
{% extends 'layout.html' %}
{% load i18n %}

{% block seotitle  %}{% trans "Income"   as seotitle  %}{{  seotitle|title }}{% endblock %}
{% block pagetitle %}{% trans "Income"   as pagetitle %}{{ pagetitle|title }}{% endblock %}
{% block subtitle  %}{% trans "delete" as subtitle  %}{{  subtitle|title }}{% endblock %}

{% block content %}
<div class="portlet light">
    <div class="portlet-title">
        <div class="caption font-red-sunglo">
          <i class="icon-speech font-red-sunglo"></i>
          <span class="caption-subject bold uppercase">
            {% blocktrans with  item=object.invoice_number %}¿Delete income | {{ item }}?{% endblocktrans %}
          </span>
          <span class="caption-helper">{% trans 'answer required to continue...' %}</span>
        </div>
        <div class="actions"></div>
    </div>
    <div class="portlet-body">
      <form action="" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">{% trans 'Yes, delete' %}</button>
        <a class="btn btn-default" href="{% url 'income:income_list' %}">{% trans 'Cancel' %}</a>
      </form>
  </div>
</div>
{% endblock content %}

apps/income/templates/income/income_form.html
{% extends 'layout.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block content %}
 <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class='row'>
       <div class="col-md-6 col-md-push-6">
            {% include "inc/portlet/base.html" with title='Añadir entrada' icon='flaticon-diagram' %}
                <div class="overflow-hidden">
                    <div class="row">
                        <div class="col-sm-6">
                            {% include "inc/form/field_date.html" with field=form.date %}
                            {% include "inc/form/field_date.html" with field=form.date_payment %}
                            {% include "inc/form/field.html" with field=form.service  %}
                            {% include "inc/form/field.html" with field=form.invoice_number %}
                            {% include "inc/form/field.html" with field=form.total %}
                            {% include "inc/form/field_file.html" with field=form.invoice_file %}

                        </div>
                    </div>
                </div>
            {% include "inc/portlet/end.html" %}
        </div>
        <div class="col-md-6 col-md-pull-6">
            {% include "inc/portlet/base.html" with title='Comments' icon='flaticon2-files-and-folders' %}
                <div class="overflow-hidden">
                    <div class="row">
                        <div class="col-sm-12">
                            {% include "inc/form/field_textarea.html" with field=form.comment %}
                        </div>
                    </div>
                </div>
            {% include "inc/portlet/end.html" %}
        </div>
        <div class="col-md-12">
            {% include "inc/portlet/base.html" %}
                <div class="kt-section__content kt-section__content--solid">
                <button type="submit" name="submit" class="btn btn-secondary btn-hover-brand" >{% trans "Save " %}</button>
                <a class="btn btn-secondary btn-hover-brand" onclick="window.history.back()"> <i class="fa fa-reply"></i> {% trans 'Go Back' %}</a>
                {% if object %}
                <a class="btn btn-danger float-right" href="{% url 'income:income_delete' object.pk %}"> <i class="fa fa-trash"></i> {% trans 'Delete' %}</a>
                {% endif %}
                </div>
            {% include "inc/portlet/end.html" %}
        </div>
    </div>
</form>
{% endblock content %}

{% block js %}
   {% if update %}
    <script type="text/javascript">
       $(function() {
        $( ".datepicker" ).datepicker({ format: 'dd/mm/yyyy', orientation: "bottom auto" });

      });
    </script>
    {% else %}
     <script type="text/javascript">
       $(function() {
            $( ".datepicker" ).datepicker({ format: 'dd/mm/yyyy', orientation: "bottom auto" }).datepicker("setDate", new Date());;
      });
    </script>
    {% endif %}
{% endblock js %}

apps/income/templates/income/income_list.html
{% extends 'layout.html' %}
{% load i18n %}
{% load custom_filters %}

{% block content %}

<div class="kt-portlet">
    <div class="kt-portlet__head">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="flaticon-statistics"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                {% trans 'Complete List' %}
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-actions">
                <a href="{% url 'income:income_create' %}" ><i class="fa fa-plus"></i></a>
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">
        {% if expense_list %}
            <table
                id="datatable1"
                class="table table-striped table-bordered table-hover
                       table-checkable order-column">
                <thead>
                    <tr>
                        <th>Nº</th>
                        <th>{% trans 'date' %}</th>
                        <th>{% trans 'agent' %}</th>
                        <th>{% trans 'local' %}</th>
                        <th>{% trans 'status' %}</th>
                        <th>{% trans 'total' %}</th>
                        <th>{% trans 'machine' %}</th>
                        {% if edit %}
                            <th>{% trans "Update" %}</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                  {% for item in expense_list %}
                    <tr class="odd gradeX" style="background-color: #F59898 !important;" >
                        <td style="background-color: #F59898 !important;">
                        {% if item.invoice_file %}
                            <a href="{{ item.invoice_file.url }}" target="expense">
                                {{ item.invoice_number }}
                            </a>
                        {% else %}
                            {{ item.invoice_number }}
                        {% endif %}
                        </td>
                        <td data-order="{{ item.date|date:'d-m-Y' }}">
                            {{ item.date|date:'d/m/Y' }}
                        </td>
                        <td>
                            {{ item.user|default:"" }}
                        </td>
                        <td >
                            {{ item.local|default:"" }}
                        </td>
                        <td data-order="{{ item.date_payment|date:'Y-m-d' }}"
                            class="">
                            {% if item.date_payment %}
                                <span class="kt-badge kt-badge--inline kt-badge--success" title="{{ item.date_payment }}">{% trans "paid" %}</span>
                            {%else%}
                                <span class="kt-badge kt-badge--inline kt-badge--warning">{% trans "pending" %}</span>
                            {% endif %}
                        </td>
                        <td>-{{ item.total | currency }}</td>
                        <td>{{ item.machine }}</td>
                        {% if edit %}
                        <td>
                            <a
                                href="{{ item.get_absolute_url }}"
                                target="update_expense" title="{% trans 'Update' %}">
                                <i class="flaticon-cogwheel-1"></i>
                            </a>
                        </td>
                        {% endif %}
                    </tr>
                  {% endfor %}
                  {% for item in income_list %}
                    <tr class="odd gradeX">
                        <td>
                        {% if item.invoice_file %}
                            <a href="{{ item.invoice_file.url }}" target="income">
                                {{ item.invoice_number }}
                            </a>
                        {% else %}
                            {{ item.invoice_number }}
                        {% endif %}
                        </td>
                        <td data-order="{{ item.date|date:'d-m-Y' }}">
                            {{ item.date|date:'d/m/Y' }}
                        </td>
                        <td>
                            {{ item.user|default:"" }}
                        </td>
                        <td >
                            {{ item.local|default:"" }}
                        </td>
                        <td data-order="{{ item.date_payment|date:'Y-m-d' }}"
                            class="">
                            {% if item.date_payment %}
                                <span class="kt-badge kt-badge--inline kt-badge--success" title="{{ item.date_payment }}">{% trans "paid" %}</span>
                            {%else%}
                                <span class="kt-badge kt-badge--inline kt-badge--warning">{% trans "pending" %}</span>
                            {% endif %}
                        </td>
                        <td>{{ item.total | currency }}</td>
                        <td>{{ item.machine }}</td>
                        {% if edit %}
                        <td>
                            <a
                                href="{{ item.get_absolute_url }}"
                                target="update_income" title="{% trans 'Update' %}">
                                <i class="flaticon-cogwheel-1"></i>
                            </a>
                        </td>
                        {% endif %}
                    </tr>
                  {% endfor %}

                </tbody>
            </table>
            {% else %}
              {% trans 'No Incomes' %}
            {% endif %}
        </div>
    </div>
    <!-- END SAMPLE TABLE PORTLET-->


{% endblock content %}

{% block js %}
    <script type="text/javascript">
    $(document).ready( function () {
    $('#datatable1').DataTable();
    } );
    document.addEventListener("DOMContentLoaded", function(event) {
    $( ".datepicker" ).datepicker({ format: 'dd-mm-yyyy' }).datepicker();;
    });
    </script>
{% endblock js %}