core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.frontend.views import home, contact
from apps.worker.views import login, SignOutView

from django.conf.urls.i18n import i18n_patterns

admin.site.site_header = settings.SITE_HEADER
admin.site.site_title = settings.SITE_TITLE
admin.site.index_title = settings.INDEX_TITLE

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('summernote/', include('django_summernote.urls')),
    path('blog/', include('apps.blog.urls')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('login/', login, name='login'),
    path('logout/', SignOutView.as_view(), name='logout'),
    path('dashboard/', include('apps.dashboard.urls')),
    path('contact/', contact, name='contact'),
)

apps/blog/models.py
from django.db import models

from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from easy_thumbnails.fields import ThumbnailerImageField

from core.abstract import (
    ActiveModel,
    SeoModel,
    SlugModel,
    DescriptionModel
    )


# Create your models here.
class BlogCategory(ActiveModel):
    name = models.CharField(_('name'), max_length=200, null=True, blank=True)
    description_short = models.TextField(_('description short'), null=True, blank=True)
    image = models.ImageField(
        _('image'),
        null=True,
        blank=True,
        upload_to="blogcategory/")

    class meta:
        verbose_name = _('category blog')
        verbose_name_plural = _('categories blogs')

    def __str__(self):
        return '{}'.format(self.name)

    def get_view_url(self):
        return reverse('blog:blog_category', kwargs={'category': self.name})


class BlogPost(ActiveModel, SlugModel, DescriptionModel, SeoModel):

    author = models.CharField(_('author'), max_length=200, null=True, blank=True)
    title = models.CharField(_('title'), max_length=200, null=True, blank=True)
    subtitle = models.CharField(_('subtitle'), max_length=200, null=True, blank=True)
    category = models.ForeignKey(
        BlogCategory,
        related_name='categories',
        on_delete=models.CASCADE
        )
    icon = models.CharField(_('icon'), null=True, blank=True, max_length=200)
    name_image = models.CharField(_('name image'), max_length=200, null=True, blank=True)
    image = ThumbnailerImageField(
        _('image'),
        upload_to='blog/',
        default='blog/default.jpg',
        blank=True
        )

    class meta:
        verbose_name = _('blog')
        verbose_name_plural = _('blogs')

    def __str__(self):
        return '{}'.format(self.title)

    def get_view_url(self):
        return reverse('blog:blog_post', kwargs={'slug': self.slug})

templates/block/_block_alerts.html
{% load i18n %}

<div class="col-xl-12">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'success'%}success{% endif %} fade show" role="alert">
            <div class="alert-icon"><i class="{% if message.tags == 'error' %}flaticon-warning{% elif message.tags == 'success'%}flaticon2-check-mark{% endif %}"></i></div>
            <div class="alert-text">{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}{% trans "important"|capfirst %}: {% endif %}{{ message|capfirst }}</div>
            <div class="alert-close">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"><i class="la la-close"></i></span>
                </button>
            </div>
        </div>
        {% endfor %}
    {% endif %}
</div>

templates/block/_block_articles.html
<article>
<div class="row">
<div class="large-6 columns">
<p><img src="https://placehold.it/600x370&text=Look at me!" alt="image for article" alt="article preview image"></p>
</div>
<div class="large-6 columns">
<h5><a href="#">'Death Star' Vaporizes Its Own Planet</a></h5>
<p>
<span><i class="fi-torso"> By Thadeus &nbsp;&nbsp;</i></span>
<span><i class="fi-calendar"> 11/23/16 &nbsp;&nbsp;</i></span>
<span><i class="fi-comments"> 6 comments</i></span>
</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae impedit beatae, ipsum delectus aperiam nesciunt magni facilis ullam.</p>
</div>
</div>
<hr>

<ul class="pagination" role="navigation" aria-label="Pagination">
<li class="disabled">Previous <span class="show-for-sr">page</span></li>
<li class="current"><span class="show-for-sr">You're on page</span> 1</li>
<li><a href="#" aria-label="Page 2">2</a></li>
<li><a href="#" aria-label="Page 3">3</a></li>
<li><a href="#" aria-label="Page 4">4</a></li>
<li><a href="#" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
</ul>

</article>

templates/block/_block_image.html
<hr>
    <div class="row column">
    <h4 style="margin: 0;" class="text-center">{{ title|title }}</h4>
    </div>
    <hr>
    <div class="row small-up-3 medium-up-4 large-up-5">
    <div class="column">
    <img src="https://placehold.it/400x370&text=Look at me!" alt="image for article">
    </div>
    <div class="column">
    <img src="https://placehold.it/400x370&text=Look at me!" alt="image for article">
    </div>
    <div class="column">
    <img src="https://placehold.it/400x370&text=Look at me!" alt="image for article">
    </div>
    <div class="column show-for-medium">
    <img src="https://placehold.it/400x370&text=Look at me!" alt="image for article">
    </div>
    <div class="column show-for-large">
    <img src="https://placehold.it/400x370&text=Look at me!" alt="image for article">
    </div>
    </div>
<hr>

templates/block/_block_links.html
{% load mptt_tags %}
{% load model_tags %}

{% recursetree node %}

{% if hook == 'hf' %}

    <ul class="menu vertical medium-horizontal expanded medium-text-center" data-responsive-menu="drilldown medium-dropdown">
        <li class="has-submenu">
            <a href="{% if node.url %}/{{ lang }}{{ node.url }}{% else %}{% endif %}">{{ node.name }}</a>
            {%  children node 'hf' lang %}
        </li>
    </ul>

{% elif hook == 'hd' %}
    <li class="kt-menu__item  kt-menu__item--submenu kt-menu__item--rel" data-ktmenu-submenu-toggle="click" aria-haspopup="true"><a href='{% if node.url %}/{{ lang }}{{ node.url }}{% else %}{% endif %}' class="kt-menu__link kt-menu__toggle"><span class="kt-menu__link-text">{{ node.name|title }}</span><i class="kt-menu__ver-arrow la la-angle-right"></i></a>
        {%  children node %}
    </li>
{% endif %}

{% endrecursetree %}

templates/block/_block_mapleaflet.html
{% load leaflet_tags %}

{% leaflet_map "prueba" callback="window.map_init_basic" %}

{% block js %}
    <script type="text/javascript">
    function map_init_basic (map, options) {
        map.setView([ {{ location.latitude }}, {{ location.longitude }} ], 16);

            var content = "{% if location.name %}{{ location.name|title }} {% else %} {{ location.full_name }}{% endif %}"+
                      "<br />{{ location.latitude|floatformat:7 }},{{ location.longitude|floatformat:7 }}";

            L.marker([ {{ location.latitude }}, {{ location.longitude }} ], {
                draggable: false,        // Make the icon dragable
                title: '{{ location.name|title }}',     // Add a title
                opacity: 0.5}
            ).addTo(map)
            .bindPopup(content)
            .openPopup();

    }
    </script>
{% endblock js %}

templates/block/_block_publicity.html
<div class="row column">
    <p class="lead">{{ title|title }}</p>
    <p><img src="https://placehold.it/400x300&text=Buy Me!" alt="{{ item.alt }}"></p>
</div>

templates/block/_block_socials.html
{% load i18n %}
<ul class="social">
    {% for item in socials %}
        <li><a href="{{ item.url }}" title="{{ item.get_name_display }}" ><i class="{{ item.name }}"></i></a></li>
    {% endfor %}
</ul>

templates/block/block_service.html
<div class="services_block padbot40" data-appear-top-offset="-200" data-animated="fadeInUp">
        <!-- CONTAINER -->
        <div class="container">

            <!-- ROW -->
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-ss-12 margbot30">
                    <a class="services_item" href="javascript:void(0);" >
                        <p><b>Easy</b> Customize</p>
                        <span>Quality and very comfortable design, does not hurt the eyes and pleasant to use.</span>
                    </a>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-ss-12 margbot30">
                    <a class="services_item" href="javascript:void(0);" >
                        <p><b>Modern</b> Design</p>
                        <span>Quality and unique design that meets all the requirements and trends of modern web design.</span>
                    </a>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-ss-12 margbot30">
                    <a class="services_item" href="javascript:void(0);" >
                        <p><b>Responsive</b> Design</p>
                        <span>Design that will be equally beautifully displayed on all your devices, tablet, smartphone or computer.</span>
                    </a>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6 col-ss-12 margbot30">
                    <a class="services_item" href="javascript:void(0);" >
                        <p><b>Free</b> Updates & Support</p>
                        <span>Hour and great support template. You can always ask a question and we will help you.</span>
                    </a>
                </div>
            </div><!-- //ROW -->
        </div><!-- //CONTAINER -->
    </div>