apps/dashboard/urls.py
from django.urls import path

from apps.worker.views import create_worker, list_worker, view_worker
from apps.patient.views import create_patient, list_patient, view_patient
from apps.blog.views import create_blog, list_blog
from apps.schedule.views import create_event, list_event, print_event
from .views import home, calendar


app_name = "dashboard"
urlpatterns = [

    path('administration/create_worker/', create_worker, name='create_worker'),
    path('administration/list_worker/', list_worker, name='list_worker'),
    path('administration/view_worker/<dni>', view_worker, name='view_worker'),

    path('administration/create_patient/', create_patient, name='create_patient'),
    path('administration/list_patient/', list_patient, name='list_patient'),
    path('administration/view_patient/<dni>', view_patient, name='view_patient'),

    path('schedule/', calendar, name='calendar'),
    path('schedule/create_event/<dni_worker>/<dni_patient>/', create_event, name='create_event'),
    path('schedule/list_event/', list_event, name='list_event'),
    path('schedule/print_event/<year>/<month>/<patient>', print_event, name='print_event'),

    path('blog/create-blog/', create_blog, name='create_blog'),
    path('blog/list-blog/', list_blog, name='list_blog'),
    path('blog/view-blog/<pk>', list_blog, name='list_blog'),

    path('', home, name='home'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.frontend.views import home, contact
from apps.worker.views import login, SignOutView

from django.conf.urls.i18n import i18n_patterns

admin.site.site_header = settings.SITE_HEADER
admin.site.site_title = settings.SITE_TITLE
admin.site.index_title = settings.INDEX_TITLE

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('summernote/', include('django_summernote.urls')),
    path('blog/', include('apps.blog.urls')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('login/', login, name='login'),
    path('logout/', SignOutView.as_view(), name='logout'),
    path('dashboard/', include('apps.dashboard.urls')),
    path('contact/', contact, name='contact'),
)

apps/dashboard/views.py
from django.utils import timezone


from django.shortcuts import render
from django.utils.translation import gettext_lazy as _

from apps.schedule.models import Event


def home(request):
    worker_events = ''
    if request.user.is_staff:
        context = {

        }
        return render(request, 'dashboard/dashboard_admin.html', context)

    try:
        worker_events = Event.objects.filter(worker__user__username=request.user.username)
    except Event.DoesNotExist:
        worker_events = ''

    context = {
        'worker_events': worker_events,
    }

    return render(request, 'dashboard/dashboard_worker.html', context)


def calendar(request):
    try:
        items = Event.objects.all()
    except Event.DoesNotExist:
        items = ''

    context = {
        'items': items,
        'month': _('month')
    }

    return render(request, 'dashboard/view/calendar_list.html', context)

apps/dashboard/templates/dashboard/view/blog_list.html
{% extends 'dashboard/layout.html' %}
{% load static %}
{% load i18n %}
{% block css %}
    <link href="{% static 'dashboard/css/demo1/pages/wizard/wizard-4.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}

{% block content %}
<div class="row">
    {% for item in items %}

        <div class="col-xl-4">

            <div class="kt-portlet kt-portlet--height-fluid">
                <div class="kt-portlet__body kt-portlet__body--fit">

                    <!--begin::Widget -->
                    <div class="kt-widget kt-widget--project-1">
                        <div class="kt-widget__head d-flex">
                            <div class="kt-widget__label">
                                <div class="kt-widget__media kt-widget__media--m">
                                    <span class="kt-userpic kt-userpic--md kt-userpic--circle kt-hidden-">
                                        <img src="{% if item.image %}{{ item.image.url }}{% endif %}" alt="image">
                                    </span>
                                    <span class="kt-userpic kt-userpic--md kt-userpic--circle kt-hidden">
                                        <img src="./assets/media/users/100_12.jpg" alt="image">
                                    </span>
                                </div>
                                <div class="kt-widget__info kt-padding-0 kt-margin-l-15">
                                    <a href="#" class="kt-widget__title">
                                       {{ item.title }}
                                    </a>
                                    <span class="kt-widget__desc">
                                        {{ item.subtitle|default:'' }}
                                    </span>
                                </div>
                            </div>
                            {% comment %}

                            <div class="kt-widget__toolbar">
                                <a href="#" class="btn btn-clean btn-sm btn-icon btn-icon-md" data-toggle="dropdown">
                                    <i class="flaticon-more-1"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right">
                                    <ul class="kt-nav">
                                        <li class="kt-nav__item">
                                            <a href="#" class="kt-nav__link">
                                                <i class="kt-nav__link-icon flaticon2-line-chart"></i>
                                                <span class="kt-nav__link-text">Reports</span>
                                            </a>
                                        </li>
                                        <li class="kt-nav__item">
                                            <a href="#" class="kt-nav__link">
                                                <i class="kt-nav__link-icon flaticon2-send"></i>
                                                <span class="kt-nav__link-text">Messages</span>
                                            </a>
                                        </li>
                                        <li class="kt-nav__item">
                                            <a href="#" class="kt-nav__link">
                                                <i class="kt-nav__link-icon flaticon2-pie-chart-1"></i>
                                                <span class="kt-nav__link-text">Charts</span>
                                            </a>
                                        </li>
                                        <li class="kt-nav__item">
                                            <a href="#" class="kt-nav__link">
                                                <i class="kt-nav__link-icon flaticon2-avatar"></i>
                                                <span class="kt-nav__link-text">Members</span>
                                            </a>
                                        </li>
                                        <li class="kt-nav__item">
                                            <a href="#" class="kt-nav__link">
                                                <i class="kt-nav__link-icon flaticon2-settings"></i>
                                                <span class="kt-nav__link-text">Settings</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                            {% endcomment %}
                        </div>
                        <div class="kt-widget__body">
                            <span class="kt-widget__text kt-margin-t-0 kt-padding-t-5">
                                {{ item.description_short|truncatechars:150 }}
                            </span>
                            <div class="kt-widget__stats kt-margin-t-20">
                                <div class="kt-widget__item d-flex align-items-center kt-margin-r-30">
                                    <span class="kt-widget__date kt-padding-0 kt-margin-r-10">
                                        {% trans "start"|capfirst %}
                                    </span>
                                    <div class="kt-widget__label">
                                        <span class="btn btn-label-brand btn-sm btn-bold btn-upper">{{ item.date_active_ini|date:'d-m-y' }}</span>
                                    </div>
                                </div>
                                <div class="kt-widget__item d-flex align-items-center kt-padding-l-0">
                                    <span class="kt-widget__date kt-padding-0 kt-margin-r-10 ">
                                        {% trans "due"|capfirst %}
                                    </span>
                                    <div class="kt-widget__label">
                                        <span class="btn btn-label-danger btn-sm btn-bold btn-upper">{{ item.date_active_end|date:'d-m-y' }}</span>
                                    </div>
                                </div>
                            </div>
                            {% comment %}
                            <div class="kt-widget__container">
                                <span class="kt-widget__subtitel">Progress</span>
                                <div class="kt-widget__progress d-flex align-items-center flex-fill">
                                    <div class="progress" style="height: 5px;width: 100%;">
                                        <div class="progress-bar kt-bg-success" role="progressbar" style="width: 78%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <span class="kt-widget__stat">
                                        78%
                                    </span>
                                </div>
                            </div>
                            {% endcomment %}
                        </div>

                        <div class="kt-widget__footer">
                            <button type="button" class="btn btn-label-warning btn-lg btn-upper">{% trans "edit blog"|capfirst %}</button>
                            {% if item.active_status %}
                                <button type="button" class="btn btn-label-success btn-lg btn-upper">{% trans "active"|capfirst %}</button>
                            {% elif not item.active_status %}
                                <button type="button" class="btn btn-label-danger btn-lg btn-upper">{% trans "desactive"|capfirst %}</button>
                            {% endif %}
                        </div>

                    </div>

                    <!--end::Widget -->
                </div>
            </div>

        </div>

    {% endfor %}
</div>
{% endblock content %}

{% block js %}

{% endblock js %}

apps/dashboard/templates/dashboard/view/calendar_list.html
{% extends "dashboard/layout.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-12">

        <!--begin::Portlet-->
        <div class="kt-portlet" id="kt_portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <span class="kt-portlet__head-icon">
                        <i class="flaticon-map-location"></i>
                    </span>
                    <h3 class="kt-portlet__head-title">
                        {% trans "schedule"|capfirst %}
                    </h3>
                </div>
                <div class="kt-portlet__head-toolbar">
                    <a href="#" class="btn btn-brand btn-elevate">
                        <i class="la la-plus"></i>
                        Add Event
                    </a>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div id="kt_calendar"></div>
            </div>
        </div>

        <!--end::Portlet-->
    </div>
</div>
{% endblock content %}
{% block js %}

<script type="text/javascript">
    var KTCalendarBasic = function() {

    return {
        //main function to initiate the module
        init: function() {
            var todayDate = moment().startOf('day');
            var YM = todayDate.format('YYYY-MM');
            var YESTERDAY = todayDate.clone().subtract(1, 'day').format('YYYY-MM-DD');
            var TODAY = todayDate.format('YYYY-MM-DD');
            var TOMORROW = todayDate.clone().add(1, 'day').format('YYYY-MM-DD');

            var calendarEl = document.getElementById('kt_calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                plugins: [ 'interaction', 'dayGrid', 'timeGrid', 'list' ],
                locale: '{{ lang }}',
                isRTL: KTUtil.isRTL(),
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay'
                },

                height: 800,
                contentHeight: 780,
                aspectRatio: 3,  // see: https://fullcalendar.io/docs/aspectRatio

                nowIndicator: true,

                views: {
                    dayGridMonth: { buttonText: 'month' },
                    timeGridWeek: { buttonText: 'week' },
                    timeGridDay: { buttonText: 'day' }
                },

                defaultView: 'dayGridMonth',
                defaultDate: TODAY,

                editable: true,
                eventLimit: true, // allow "more" link when too many events
                navLinks: true,
                events: [

                {% for item in items %}
                    {
                        title: '{{ item.worker.user.first_name|title }}-{{item.patient.first_name|title}}',
                        start: '{{ item.date|date:'Y-m-d' }}T{{ item.start_time|date:'H:i' }}',
                        description: '{{ item.description }}',
                        end: '{{ item.date|date:'Y-m-d' }}T{{ item.end_time|date:'H:i'}}',
                        className: "fc-event-danger fc-event-solid-warning"
                    },
                {% endfor %}

                ],

                eventRender: function(info) {
                    var element = $(info.el);

                    if (info.event.extendedProps && info.event.extendedProps.description) {
                        if (element.hasClass('fc-day-grid-event')) {
                            element.data('content', info.event.extendedProps.description);
                            element.data('placement', 'top');
                            KTApp.initPopover(element);
                        } else if (element.hasClass('fc-time-grid-event')) {
                            element.find('.fc-title').append('<div class="fc-description">' + info.event.extendedProps.description + '</div>');
                        } else if (element.find('.fc-list-item-title').lenght !== 0) {
                            element.find('.fc-list-item-title').append('<div class="fc-description">' + info.event.extendedProps.description + '</div>');
                        }
                    }
                }
            });

            calendar.render();
        }
    };
}();

jQuery(document).ready(function() {
    KTCalendarBasic.init();
});
</script>
{% endblock js %}

apps/dashboard/templates/dashboard/view/event_list.html
{% extends 'dashboard/layout.html' %}
{% load static %}
{% load i18n %}
{% block css %}
    <link href="{% static 'dashboard/css/demo1/pages/wizard/wizard-4.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}
{% block content %}
<div class="kt-portlet">
    <div class="kt-portlet__head">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="flaticon-statistics"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                {% trans "events list"|title %}
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-actions">
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">


    {% regroup items by patient as events_by_patient %}
    {% for items in events_by_patient %}
    <div class="row">
        <div class="col-xl-4 col-md-4 col-lg-4">
        <h5>{% trans "auxiliar"|title %}:{{ request.user.first_name }}</h5>
        </div>
        <div class="col-xl-4 col-md-4 col-lg-4">
         <h5>{% trans "user"|title %}: {{ items.grouper }}</h5>
        </div>
        <div class="col-xl-4 col-md-4 col-lg-4">
         <h5>{% trans "month"|title %}: {%  now 'F' %}</h5>
        </div>
    </div>
         <table
            id="datatable1"
            class="table table-striped table-bordered table-hover
                   table-checkable order-column">
            <thead>
                <tr>
                    <th>{% trans 'date' %}</th>
                    <th>{% trans 'start time' %}</th>
                    <th>{% trans 'end time' %}</th>
                    <th>{% trans 'total' %}</th>
                </tr>
            </thead>
            <tbody>
        {% for item in items.list %}
            <tr class="odd gradeX">
                <td>{{ item.date|date:'d-m-Y' }}</td>
                <td>{{ item.start_time }}</td>
                <td>{{ item.end_time }}</td>
                <td>{{ item.time }} min</td>
            </tr>
        {% endfor %}
            </tbody>
        </table>
    {% endfor %}
    </div>
</div>

{% endblock content %}

{% block js %}
    <script type="text/javascript">
    $(document).ready( function () {
    $('#datatable1').DataTable();
    } );
    </script>
{% endblock js %}

apps/dashboard/templates/dashboard/view/patient_item.html
{% extends 'dashboard/layout.html' %}
{% load static %}
{% load i18n %}
{% block css %}
    <link href="{% static 'dashboard/css/demo2/pages/wizard/wizard-4.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}
{% block subheader %}

    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-container">
            <div class="kt-subheader__main">
                <button class="kt-subheader__mobile-toggle kt-subheader__mobile-toggle--left" id="kt_subheader_mobile_toggle"><span></span></button>
                <h3 class="kt-subheader__title">
                    {{ app_name|title }} </h3>
                <span class="kt-subheader__separator kt-hidden"></span>
                <div class="kt-subheader__breadcrumbs">
                    <a href="" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{% url 'dashboard:home' %}" class="kt-subheader__breadcrumbs-link">
                        {% trans "dashboard"|capfirst %} </a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{% url 'dashboard:list_patient' %}" class="kt-subheader__breadcrumbs-link">
                        {% trans "patient"|capfirst %} </a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="" class="kt-subheader__breadcrumbs-link">
                        {{ item.full_name }} </a>

                    <!-- <span class="kt-subheader__breadcrumbs-link kt-subheader__breadcrumbs-link--active">Active link</span> -->
                </div>
            </div>

            <div class="kt-subheader__toolbar">
                <div class="kt-subheader__wrapper">
                    <a href="#" class="btn kt-subheader__btn-primary">
                        {% now 'l, d F Y' %}&nbsp;
                        <i class="flaticon2-calendar-1"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock subheader %}
{% block content %}

    <div class="kt-grid kt-grid--desktop kt-grid--ver kt-grid--ver-desktop kt-app">

        <!--Begin:: App Aside Mobile Toggle-->
        <button class="kt-app__aside-close" id="kt_user_profile_aside_close">
            <i class="la la-close"></i>
        </button>

        <!--End:: App Aside Mobile Toggle-->

        <!--Begin:: App Aside-->
        <div class="kt-grid__item kt-app__toggle kt-app__aside" id="kt_user_profile_aside">

            <!--Begin::Portlet-->
            <div class="kt-portlet kt-portlet--height-fluid-">
                <div class="kt-portlet__head kt-portlet__head--noborder">
                    <div class="kt-portlet__head-label">
                        <h3 class="kt-portlet__head-title">
                        </h3>
                    </div>
                </div>
                <div class="kt-portlet__body">

                    <!--begin::Widget -->
                    <div class="kt-widget kt-widget--user-profile-2">
                        <div class="kt-widget__head">
                            <div class="kt-widget__media">
                                <img class="kt-widget__img kt-hidden-" src="{{ item.image.90w.url }}" alt="image">
                                <div class="kt-widget__pic kt-widget__pic--danger kt-font-danger kt-font-boldest kt-font-light kt-hidden">
                                    {{ item.first_name|truncatewords:'1' }}
                                </div>
                            </div>
                            <div class="kt-widget__info">
                                <a href="#" class="kt-widget__username">
                                    {{ item.full_name }}
                                </a>
                                <span class="kt-widget__desc">
                                    {% trans "patient"|capfirst %}
                                </span>
                            </div>
                        </div>
                        <div class="kt-widget__body">
                            <div class="kt-widget__section">
                                Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical.
                            </div>
                            <div class="kt-widget__content">
                                <div class="kt-widget__stats kt-margin-r-20">
                                    <div class="kt-widget__icon">
                                        <i class="flaticon-piggy-bank"></i>
                                    </div>
                                    <div class="kt-widget__details">
                                        <span class="kt-widget__title">Earnings</span>
                                        <span class="kt-widget__value"><span>$</span>249,500</span>
                                    </div>
                                </div>
                                <div class="kt-widget__stats">
                                    <div class="kt-widget__icon">
                                        <i class="flaticon-pie-chart"></i>
                                    </div>
                                    <div class="kt-widget__details">
                                        <span class="kt-widget__title">Net</span>
                                        <span class="kt-widget__value"><span>$</span>84,060</span>
                                    </div>
                                </div>
                            </div>
                            <div class="kt-widget__item">
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">{% trans "email"|capfirst %}:</span>
                                    <a href="mailto:{{ item.email }}" class="kt-widget__data">{{ item.email }}</a>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">{% trans "phone"|capfirst %}:</span>
                                    <a href="tel:{{ item.phone }}" class="kt-widget__data">{{ item.phone }}</a>
                                </div>
                                <div class="kt-widget__contact">
                                    <span class="kt-widget__label">{% trans "address"|capfirst %}:</span>
                                    <span class="kt-widget__data">{{ item.address }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="kt-widget__footer">
                            <button type="button" class="btn btn-label-success btn-lg btn-upper">{% trans "send a message" %}</button>
                        </div>
                    </div>

                </div>
            </div>

        </div>

        <!--Begin:: App Content-->
        <div class="kt-grid__item kt-grid__item--fluid kt-app__content">
            <div class="row">
                <div class="col">

                    <!--Begin::Section-->
                    <div class="kt-portlet">
                        <div class="kt-portlet__body kt-portlet__body--fit">
                            <div class="row row-no-padding row-col-separator-xl">
                                <div class="col-md-12 col-lg-12 col-xl-6">

                                    <!--begin:: Widgets/Stats2-2 -->
                                    <div class="kt-widget1">
                                        <div class="kt-widget1__item">
                                            <div class="kt-widget1__info">
                                                <h3 class="kt-widget1__title">{{item.contact_name}}</h3>
                                                <span class="kt-widget1__desc">{% trans "contact name"|title %}</span>
                                            </div>

                                        </div>
                                        <div class="kt-widget1__item">
                                            <div class="kt-widget1__info">
                                                <h3 class="kt-widget1__title"><a href="tel:{{item.contact_phone}}" title="{% trans 'phone' %}">{{item.contact_phone}}</a></h3>
                                                <span class="kt-widget1__desc">{% trans "contact phone"|title %}</span>
                                            </div>
                                        </div>
                                        <div class="kt-widget1__item">
                                            <div class="kt-widget1__info">
                                               <h3 class="kt-widget1__title"><a href="mailto:{{item.contact_email}}" title="{% trans 'email' %}">{{item.contact_email}}</a></h3>
                                                <span class="kt-widget1__desc">{% trans "contact email"|title %}</span>
                                            </div>
                                           </div>
                                    </div>

                                    <!--end:: Widgets/Stats2-2 -->
                                </div>
                                <div class="col-md-12 col-lg-12 col-xl-6">

                                    <!--begin:: Widgets/Stats2-3 -->
                                    <div class="kt-widget1">
                                        <div class="kt-widget1__item">
                                            <div class="kt-widget1__info">
                                                <h3 class="kt-widget1__title">{{item.address}}</h3>
                                                <span class="kt-widget1__desc">{% trans "address"|title %}</span>
                                            </div>

                                        </div>
                                        <div class="kt-widget1__item">
                                            <div class="kt-widget1__info">
                                                   <h3 class="kt-widget1__title">{{item.city}}</h3>
                                                <span class="kt-widget1__desc">{% trans "city"|title %}</span>
                                            </div>

                                        </div>
                                        <div class="kt-widget1__item">
                                            <div class="kt-widget1__info">
                                               <h3 class="kt-widget1__title">{{item.state}}</h3>
                                                <span class="kt-widget1__desc">{% trans "state"|title %}</span>
                                            </div>
                                        </div>
                                    </div>

                                    <!--end:: Widgets/Stats2-3 -->
                                </div>
                                <div class="col-md-12 col-lg-12 col-xl-12">
                                    {% include "block/_block_mapleaflet.html" with location=item %}
                                </div>
                            </div>
                        </div>
                    </div
                    <!--End::Section-->
                </div>
            </div>
        </div>

        <!--End:: App Content-->
    </div>

{% endblock content %}

{% block js %}
    {% load leaflet_tags %}
    {% leaflet_js %}
    {% leaflet_css %}
    <script src="{% static 'dashboard/js/demo2/pages/custom/user/profile.js' %}" type="text/javascript"></script>
{% endblock js %}