apps/dashboard/urls.py
from django.urls import path

from apps.worker.views import create_worker, list_worker, view_worker
from apps.patient.views import create_patient, list_patient, view_patient
from apps.blog.views import create_blog, list_blog
from apps.schedule.views import create_event, list_event, print_event
from .views import home, calendar


app_name = "dashboard"
urlpatterns = [

    path('administration/create_worker/', create_worker, name='create_worker'),
    path('administration/list_worker/', list_worker, name='list_worker'),
    path('administration/view_worker/<dni>', view_worker, name='view_worker'),

    path('administration/create_patient/', create_patient, name='create_patient'),
    path('administration/list_patient/', list_patient, name='list_patient'),
    path('administration/view_patient/<dni>', view_patient, name='view_patient'),

    path('schedule/', calendar, name='calendar'),
    path('schedule/create_event/<dni_worker>/<dni_patient>/', create_event, name='create_event'),
    path('schedule/list_event/', list_event, name='list_event'),
    path('schedule/print_event/<year>/<month>/<patient>', print_event, name='print_event'),

    path('blog/create-blog/', create_blog, name='create_blog'),
    path('blog/list-blog/', list_blog, name='list_blog'),
    path('blog/view-blog/<pk>', list_blog, name='list_blog'),

    path('', home, name='home'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.frontend.views import home, contact
from apps.worker.views import login, SignOutView

from django.conf.urls.i18n import i18n_patterns

admin.site.site_header = settings.SITE_HEADER
admin.site.site_title = settings.SITE_TITLE
admin.site.index_title = settings.INDEX_TITLE

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('summernote/', include('django_summernote.urls')),
    path('blog/', include('apps.blog.urls')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('login/', login, name='login'),
    path('logout/', SignOutView.as_view(), name='logout'),
    path('dashboard/', include('apps.dashboard.urls')),
    path('contact/', contact, name='contact'),
)

templates/inc/admin_info.html
    {% load i18n %}

    <div class="row">
        <div class="col-lg-3 col-sm-6">
            <div class="kt-portlet kt-iconbox kt-iconbox--success kt-iconbox--animate-faster">
                <div class="kt-portlet__body">
                    <div class="kt-iconbox__body">
                        <div class="kt-iconbox__icon">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <rect id="bound" x="0" y="0" width="24" height="24"/>
                                    <path d="M14.8520384,9 L15.7780576,12 L8.22196243,12 L9.14797495,9 L14.8520384,9 Z M13.9260192,6 L10.0739875,6 L10.7050601,3.95551581 C10.8804029,3.38745846 11.4054966,3 12,3 C12.5945036,3 13.1195978,3.38745798 13.2949418,3.95551522 L13.9260192,6 Z M16.7040768,15 L17.9387691,19 L6.06126654,19 L7.2959499,15 L16.7040768,15 Z" id="Combined-Shape" fill="#000000"/>
                                    <rect id="Rectangle" fill="#000000" opacity="0.3" x="3" y="20" width="18" height="2" rx="1"/>
                                </g>
                            </svg>
                        </div>
                        <div class="kt-iconbox__desc">
                            <h3 class="kt-iconbox__title">
                                {{ events_today }} <small></small>
                            </h3>
                            <div class="kt-iconbox__content">
                                {% trans "events for today"|capfirst %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6">
                <div class="kt-portlet kt-iconbox kt-iconbox--success kt-iconbox--animate-faster">
                    <div class="kt-portlet__body">
                        <div class="kt-iconbox__body">
                            <div class="kt-iconbox__icon">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <rect id="bound" x="0" y="0" width="24" height="24"/>
                                        <path d="M14.8520384,9 L15.7780576,12 L8.22196243,12 L9.14797495,9 L14.8520384,9 Z M13.9260192,6 L10.0739875,6 L10.7050601,3.95551581 C10.8804029,3.38745846 11.4054966,3 12,3 C12.5945036,3 13.1195978,3.38745798 13.2949418,3.95551522 L13.9260192,6 Z M16.7040768,15 L17.9387691,19 L6.06126654,19 L7.2959499,15 L16.7040768,15 Z" id="Combined-Shape" fill="#000000"/>
                                        <rect id="Rectangle" fill="#000000" opacity="0.3" x="3" y="20" width="18" height="2" rx="1"/>
                                    </g>
                                </svg>
                            </div>
                            <div class="kt-iconbox__desc">
                                <h3 class="kt-iconbox__title">
                                    {{ events_month }}
                                </h3>
                                <div class="kt-iconbox__content">
                                   {% trans "events for this month"|capfirst %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        <div class="col-lg-3 col-sm-6">
                <div class="kt-portlet kt-iconbox kt-iconbox--info kt-iconbox--animate-faster">
                    <div class="kt-portlet__body">
                        <div class="kt-iconbox__body">
                            <div class="kt-iconbox__icon">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <polygon id="Shape" points="0 0 24 0 24 24 0 24"/>
                                        <path d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z" id="Mask" fill="#000000" fill-rule="nonzero" opacity="0.3"/>
                                        <path d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z" id="Mask-Copy" fill="#000000" fill-rule="nonzero"/>
                                    </g>
                                </svg>
                            </div>
                            <div class="kt-iconbox__desc">
                                <h3 class="kt-iconbox__title">
                                    <a href="{% url 'dashboard:list_worker' %}"   title="{% trans 'list worker'|title %}">{{ num_workers }}</a>
                                </h3>
                                <div class="kt-iconbox__content">
                                    {% trans "number of workers"|capfirst %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        <div class="col-lg-3 col-sm-6">
            <div class="kt-portlet kt-iconbox kt-iconbox--default kt-iconbox--animate-faster">
                <div class="kt-portlet__body">
                    <div class="kt-iconbox__body">
                        <div class="kt-iconbox__icon">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <polygon id="Shape" points="0 0 24 0 24 24 0 24"/>
                                    <path d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z" id="Mask" fill="#000000" fill-rule="nonzero" opacity="0.3"/>
                                    <path d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z" id="Mask-Copy" fill="#000000" fill-rule="nonzero"/>
                                </g>
                            </svg>
                        </div>
                        <div class="kt-iconbox__desc">
                            <h3 class="kt-iconbox__title">
                                <a href="{% url 'dashboard:list_patient' %}" title="{% trans 'list patient' %}">{{ num_patients }}</a>
                            </h3>
                            <div class="kt-iconbox__content">
                                {% trans "number of patients"|capfirst %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/inc/admin_info2.html
    {% load i18n %}

    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="kt-portlet kt-iconbox kt-iconbox--success kt-iconbox--animate-faster">
                <div class="kt-portlet__body">
                    <div class="kt-iconbox__body">
                        <div class="kt-iconbox__icon">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <rect id="bound" x="0" y="0" width="24" height="24"/>
                                    <path d="M14.8520384,9 L15.7780576,12 L8.22196243,12 L9.14797495,9 L14.8520384,9 Z M13.9260192,6 L10.0739875,6 L10.7050601,3.95551581 C10.8804029,3.38745846 11.4054966,3 12,3 C12.5945036,3 13.1195978,3.38745798 13.2949418,3.95551522 L13.9260192,6 Z M16.7040768,15 L17.9387691,19 L6.06126654,19 L7.2959499,15 L16.7040768,15 Z" id="Combined-Shape" fill="#000000"/>
                                    <rect id="Rectangle" fill="#000000" opacity="0.3" x="3" y="20" width="18" height="2" rx="1"/>
                                </g>
                            </svg>
                        </div>
                        <div class="kt-iconbox__desc">
                            <h3 class="kt-iconbox__title">
                                {{ events_today }} <small></small>
                            </h3>
                            <div class="kt-iconbox__content">
                                {% trans "events"|capfirst %}/{% trans "today"|capfirst %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
                <div class="kt-portlet kt-iconbox kt-iconbox--success kt-iconbox--animate-faster">
                    <div class="kt-portlet__body">
                        <div class="kt-iconbox__body">
                            <div class="kt-iconbox__icon">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <rect id="bound" x="0" y="0" width="24" height="24"/>
                                        <path d="M14.8520384,9 L15.7780576,12 L8.22196243,12 L9.14797495,9 L14.8520384,9 Z M13.9260192,6 L10.0739875,6 L10.7050601,3.95551581 C10.8804029,3.38745846 11.4054966,3 12,3 C12.5945036,3 13.1195978,3.38745798 13.2949418,3.95551522 L13.9260192,6 Z M16.7040768,15 L17.9387691,19 L6.06126654,19 L7.2959499,15 L16.7040768,15 Z" id="Combined-Shape" fill="#000000"/>
                                        <rect id="Rectangle" fill="#000000" opacity="0.3" x="3" y="20" width="18" height="2" rx="1"/>
                                    </g>
                                </svg>
                            </div>
                            <div class="kt-iconbox__desc">
                                <h3 class="kt-iconbox__title">
                                    {{ events_month }}
                                </h3>
                                <div class="kt-iconbox__content">
                                   {% trans "events"|capfirst %}/{% trans "month"|capfirst %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <a href="{% url 'dashboard:list_worker' %}"   title="{% trans 'list worker'|title %}">
                <div class="kt-portlet kt-iconbox kt-iconbox--info kt-iconbox--animate-faster">
                    <div class="kt-portlet__body">
                        <div class="kt-iconbox__body">
                            <div class="kt-iconbox__icon">
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <polygon id="Shape" points="0 0 24 0 24 24 0 24"/>
                                        <path d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z" id="Mask" fill="#000000" fill-rule="nonzero" opacity="0.3"/>
                                        <path d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z" id="Mask-Copy" fill="#000000" fill-rule="nonzero"/>
                                    </g>
                                </svg>
                            </div>
                            <div class="kt-iconbox__desc">
                                <h3 class="kt-iconbox__title">
                                        {{ num_workers }}
                                </h3>
                                <div class="kt-iconbox__content">
                                    Nº {% trans "workers"|capfirst %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-3 col-md-6">
            <a href="{% url 'dashboard:list_patient' %}" title="{% trans 'list patient' %}">
            <div class="kt-portlet kt-iconbox kt-iconbox--default kt-iconbox--animate-faster">
                <div class="kt-portlet__body">
                    <div class="kt-iconbox__body">
                        <div class="kt-iconbox__icon">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <polygon id="Shape" points="0 0 24 0 24 24 0 24"/>
                                    <path d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z" id="Mask" fill="#000000" fill-rule="nonzero" opacity="0.3"/>
                                    <path d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z" id="Mask-Copy" fill="#000000" fill-rule="nonzero"/>
                                </g>
                            </svg>
                        </div>
                        <div class="kt-iconbox__desc">
                            <h3 class="kt-iconbox__title">
                                    {{ num_patients }}
                            </h3>
                            <div class="kt-iconbox__content">
                                Nº {% trans "patients"|capfirst %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </a>
        </div>
    </div>

templates/inc/children.html
{% load mptt_tags %}
{% if item %}
    {% if hook == 'hf' %}
        <ul class="submenu menu vertical" data-submenu>
            {% for items in item  %}
                <li><a href="{% if items.url %}/{{ lang }}{{ items.url }}{% else %}{% endif %}">{{ items.name|title }}</a></li>
            {% endfor %}
        </ul>
    {% elif hook == 'hd' %}
        <div class="kt-menu__submenu kt-menu__submenu--classic kt-menu__submenu--left">
            <ul class="kt-menu__subnav">
                {% for items in item %}
                    <li class="kt-menu__item " aria-haspopup="true"><a href="{% if items.url %}/{{ lang }}{{ items.url }}{% else %}/{{ lang }}/dashboard/{% endif %}" class="kt-menu__link "><i class="kt-menu__link-bullet kt-menu__link-bullet--dot"><span></span></i><span class="kt-menu__link-text">{{ items.name|title }}</span></a></li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endif %}

templates/inc/featured_posts.html
    <div class="col-lg-4 col-md-4 col-sm-6 padbot30">
            <h4><b>Featured</b> posts</h4>
            {% for item in items  %}
                <div class="recent_posts_small clearfix">
                <div class="post_item_img_small">
                    <img src="{{item.image.url}}" alt="{{item.name_image}}" />
                </div>
                  <div class="post_item_content_small">
                    <a class="title" href="{{item.get_view_url}}" >{{item.title}}</a>
                    <ul class="post_item_inf_small">
                        <li> <div class="single_blog_post_date">{{ item.date_active_ini|date:'d F Y'}}</div></li>
                    </ul>
                </div>
            </div>
            {% endfor %}

    </div>

templates/inc/options_admin_default.html
{% load i18n %}
{% load static %}
<div class="kt-portlet">
    <div class="kt-portlet__body kt-portlet__body--fit">
        <div class="kt-widget17">
            <div class="kt-widget17__visual kt-widget17__visual--chart kt-portlet-fit--top kt-portlet-fit--sides" style="background-color: #3388FF">
                <div class="kt-widget17__chart" style="height:320px;">
                    {% comment %}
                    <canvas id="kt_chart_activities"></canvas>
                    {% endcomment %}
                </div>
            </div>
            <div class="kt-widget17__stats">
                <div class="kt-widget17__items">
                    <div class="kt-widget17__item">
                        <span class="kt-widget17__icon">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <polygon id="Shape" points="0 0 24 0 24 24 0 24"/>
                                    <path d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z" id="Mask" fill="#000000" fill-rule="nonzero" opacity="0.3"/>
                                    <path d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z" id="Mask-Copy" fill="#000000" fill-rule="nonzero"/>
                                </g>
                            </svg>
                        </span>
                        <span class="kt-widget17__subtitle">
                            {% trans "patients" %}
                        </span></br>
                        <a href="{% url 'dashboard:create_patient' %}" class="btn btn-label-primary btn-pill" ><i class="kt-menu__link-icon flaticon-user-add"></i>{% trans "add new patient" %}</a><br><br>
                        <a href="{% url 'dashboard:list_patient' %}" class="btn btn-label-primary btn-pill"><i class="kt-menu__link-icon flaticon-book"></i>{% trans "patient list" %}</a><br><br>
                     </div>
                    <div class="kt-widget17__item">
                        <span class="kt-widget17__icon">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <polygon id="Shape" points="0 0 24 0 24 24 0 24"/>
                                    <path d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z" id="Mask" fill="#000000" fill-rule="nonzero" opacity="0.3"/>
                                    <path d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z" id="Mask-Copy" fill="#000000" fill-rule="nonzero"/>
                                </g>
                            </svg>
                        </span>
                        <span class="kt-widget17__subtitle">
                            {% trans "workers" %}
                        </span></br>
                        <a href="{% url 'dashboard:create_worker' %}" class="btn btn-label-primary btn-pill" ><i class="kt-menu__link-icon flaticon-user-add"></i>{% trans "add new worker" %}</a><br><br>
                        <a href="{% url 'dashboard:list_worker' %}" class="btn btn-label-primary btn-pill"><i class="kt-menu__link-icon flaticon-book"></i>{% trans "employee list" %}</a><br><br>
                    </div>
                </div>
                <div class="kt-widget17__items">
                    <div class="kt-widget17__item">
                        <span class="kt-widget17__icon">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon kt-svg-icon--warning">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <rect id="bound" x="0" y="0" width="24" height="24" />
                                    <path d="M12.7037037,14 L15.6666667,10 L13.4444444,10 L13.4444444,6 L9,12 L11.2222222,12 L11.2222222,14 L6,14 C5.44771525,14 5,13.5522847 5,13 L5,3 C5,2.44771525 5.44771525,2 6,2 L18,2 C18.5522847,2 19,2.44771525 19,3 L19,13 C19,13.5522847 18.5522847,14 18,14 L12.7037037,14 Z" id="Combined-Shape" fill="#000000" opacity="0.3" />
                                    <path d="M9.80428954,10.9142091 L9,12 L11.2222222,12 L11.2222222,16 L15.6666667,10 L15.4615385,10 L20.2072547,6.57253826 C20.4311176,6.4108595 20.7436609,6.46126971 20.9053396,6.68513259 C20.9668779,6.77033951 21,6.87277228 21,6.97787787 L21,17 C21,18.1045695 20.1045695,19 19,19 L5,19 C3.8954305,19 3,18.1045695 3,17 L3,6.97787787 C3,6.70173549 3.22385763,6.47787787 3.5,6.47787787 C3.60510559,6.47787787 3.70753836,6.51099993 3.79274528,6.57253826 L9.80428954,10.9142091 Z" id="Combined-Shape" fill="#000000" />
                                </g>
                            </svg> </span>
                        <span class="kt-widget17__subtitle">
                            {% trans "income of" %} {{ request.user.username }}
                        </span></br>
                        <a href="" class="btn btn-label-primary btn-pill" ><i class="kt-menu__link-icon flaticon-calendar-2"></i>{% trans "generate invoice" %}</a><br><br>
                        <a href="" class="btn btn-label-primary btn-pill"><i class="kt-menu__link-icon flaticon-book"></i>{% trans "invoice list" %}</a>
                        {% comment %}
                        <span class="kt-widget17__desc">
                            72 Support Cases
                        </span>
                        {% endcomment %}
                    </div>
                    <div class="kt-widget17__item">
                        <span class="kt-widget17__icon">
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon kt-svg-icon--danger">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <rect id="bound" x="0" y="0" width="24" height="24" />
                                    <path d="M3,16 L5,16 C5.55228475,16 6,15.5522847 6,15 C6,14.4477153 5.55228475,14 5,14 L3,14 L3,12 L5,12 C5.55228475,12 6,11.5522847 6,11 C6,10.4477153 5.55228475,10 5,10 L3,10 L3,8 L5,8 C5.55228475,8 6,7.55228475 6,7 C6,6.44771525 5.55228475,6 5,6 L3,6 L3,4 C3,3.44771525 3.44771525,3 4,3 L10,3 C10.5522847,3 11,3.44771525 11,4 L11,19 C11,19.5522847 10.5522847,20 10,20 L4,20 C3.44771525,20 3,19.5522847 3,19 L3,16 Z" id="Combined-Shape" fill="#000000" opacity="0.3" />
                                    <path d="M16,3 L19,3 C20.1045695,3 21,3.8954305 21,5 L21,15.2485298 C21,15.7329761 20.8241635,16.200956 20.5051534,16.565539 L17.8762883,19.5699562 C17.6944473,19.7777745 17.378566,19.7988332 17.1707477,19.6169922 C17.1540423,19.602375 17.1383289,19.5866616 17.1237117,19.5699562 L14.4948466,16.565539 C14.1758365,16.200956 14,15.7329761 14,15.2485298 L14,5 C14,3.8954305 14.8954305,3 16,3 Z" id="Rectangle-102-Copy" fill="#000000" />
                                </g>
                            </svg> </span>
                        <span class="kt-widget17__subtitle">
                            {% trans "cash of" %} {{ request.user.username }}
                        </span></br>
                            <a href="" class="btn btn-label-primary btn-pill" ><i class="kt-menu__link-icon flaticon-graphic-2"></i>{% trans "add new income" %}</a><br><br>
                            <a href="" class="btn btn-label-primary btn-pill" ><i class="kt-menu__link-icon flaticon-graphic-2"></i>{% trans "add new expense" %}</a><br><br>
                            <a href="" class="btn btn-label-primary btn-pill"><i class="kt-menu__link-icon flaticon-book"></i>{% trans "income list" %}</a><br><br>
                        {% comment %}
                            <span class="kt-widget17__desc">
                                34 Upgraded Boxes
                            </span>
                        {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>